# Generated by Django 5.1.2 on 2025-02-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='monday',
        ),
    ]
