# Generated by Django 5.1.6 on 2025-02-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_friday_afternoon_authorized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friday',
            name='afternoon_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='friday',
            name='morning_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='monday',
            name='afternoon_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='monday',
            name='morning_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='saturday',
            name='afternoon_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='saturday',
            name='morning_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='sunday',
            name='afternoon_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='sunday',
            name='morning_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='thursday',
            name='afternoon_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='thursday',
            name='morning_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='afternoon_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='morning_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='wednesday',
            name='afternoon_hours',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='wednesday',
            name='morning_hours',
            field=models.FloatField(default=4),
        ),
    ]
