# Generated by Django 5.1.6 on 2025-02-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_friday_afternoon_hours_friday_morning_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friday',
            name='sede',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='monday',
            name='sede',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='saturday',
            name='sede',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='sunday',
            name='sede',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='thursday',
            name='sede',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='sede',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='wednesday',
            name='sede',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
