# Generated by Django 5.1.6 on 2025-02-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0010_sede_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friday',
            old_name='sede',
            new_name='sede_afternoon',
        ),
        migrations.RenameField(
            model_name='monday',
            old_name='sede',
            new_name='sede_afternoon',
        ),
        migrations.RenameField(
            model_name='saturday',
            old_name='sede',
            new_name='sede_afternoon',
        ),
        migrations.RenameField(
            model_name='sunday',
            old_name='sede',
            new_name='sede_afternoon',
        ),
        migrations.RenameField(
            model_name='thursday',
            old_name='sede',
            new_name='sede_afternoon',
        ),
        migrations.RenameField(
            model_name='tuesday',
            old_name='sede',
            new_name='sede_afternoon',
        ),
        migrations.RenameField(
            model_name='wednesday',
            old_name='sede',
            new_name='sede_afternoon',
        ),
        migrations.AddField(
            model_name='friday',
            name='sede_morning',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='monday',
            name='sede_morning',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='saturday',
            name='sede_morning',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='sunday',
            name='sede_morning',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='thursday',
            name='sede_morning',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='sede_morning',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
        migrations.AddField(
            model_name='wednesday',
            name='sede_morning',
            field=models.CharField(choices=[('Barcelona', 'Barcelona'), ('San Antonio', 'San Antonio')], default='Barcelona', max_length=50),
        ),
    ]
