# Generated by Django 5.1.6 on 2025-02-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0011_rename_sede_friday_sede_afternoon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friday',
            name='last_mark_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monday',
            name='last_mark_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saturday',
            name='last_mark_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sunday',
            name='last_mark_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thursday',
            name='last_mark_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='last_mark_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wednesday',
            name='last_mark_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
